### ISSUE TITLE
Searching for statamic modifiers has weird results

### ISSUE THREAD

**Issue by edalzell** [statamic/v2-docs#113]
For example, if you search for `is_empty` it does find the modifier but ALSO finds a bunch of pages my guess is that have that in the template, but not the content, like https://docs.statamic.com/routing

**Comment by iDGS** [comment]
I guess I'm hitting this same thing, b/c (quoting convo on Slack):

I can be on this page: `https://docs.statamic.com/permissions#super-users` and enter `super` in the search field and hit the `enter` key, and it teleports me back to `https://docs.statamic.com/` and gives no results. BUT... If I type in `super` and DON'T hit the enter key, but instead mouse down to the last item in the drop-down menu that appears, and select `Show all results...` it takes me to `https://docs.statamic.com/search-results?q=super`, which is happy-campers-ville. :slightly_smiling_face:

JFYI, I also tried searching for `cache`, just to see, and hitting enter took me to `https://docs.statamic.com/knowledge-base/clear-cache`, which was at least something, so I'm guessing this is maybe a little tricky.

**Comment by jasonvarga** [comment]
The `is_empty` shows the routing page in the results because that page has the word `empty` in it. This is expected.

As for the odd `super` results, they do also contain the word super. For example, https://docs.statamic.com/modifiers/backspace contains `supercalifragilisticexpialidocious`.

The navbar dropdown results are a bit weird because we're displaying modifiers there. My guess it that the sooner the word appears in the content, the higher ranking it is given.

You aren't seeing the modifiers in the results on the actual search results page because we're grouping stuff and aren't actually showing modifiers (although we should).

Thanks for pointing it out. I wanted to add grouping to the navbar similar to the results page, and/or adjust our ranking algorithm.

**Comment by iDGS** [comment]
I agree that `supercalifragilisticexpialidocious` is a valid hit when searching for `super`. No complaint. The bigger mystery to me was that typing `super` in the search field _and_ hitting the [enter] key yielded no results at all. But I gather you're on it, so thanks!
